"""
Fiscal lot persistence for USD acquisition events.
"""

from __future__ import annotations

import sqlite3
from decimal import Decimal
from typing import Optional

from backend.domain.engine import to_decimal
from backend.domain.enums import EventType
from backend.services.ptax_service import get_ptax


PRE_2024_CUTOFF = "2024-01-01"


def _is_us_asset(asset: sqlite3.Row) -> bool:
    return asset["currency"] == "USD" or asset["market"] == "US"


def create_lot_for_purchase(
    conn: sqlite3.Connection,
    event_row: sqlite3.Row | dict,
    origin_usd: Optional[str] = None,
) -> dict | None:
    """
    Create the immutable fiscal lot generated by a USD purchase event.
    """
    if event_row["event_type"] != EventType.COMPRA.value:
        return None

    asset = conn.execute(
        "SELECT id, market, currency FROM assets WHERE id = ?",
        (event_row["asset_id"],),
    ).fetchone()
    if not asset or not _is_us_asset(asset):
        return None

    existing = conn.execute(
        "SELECT * FROM fiscal_lots WHERE event_id = ?",
        (event_row["id"],),
    ).fetchone()
    if existing:
        return dict(existing)

    quantity = to_decimal(event_row["quantity"])
    total_usd = to_decimal(event_row["event_value"])
    if quantity <= 0:
        raise ValueError("Quantidade deve ser positiva para criar lote fiscal.")

    regime = "PRE_2024" if event_row["event_date"] < PRE_2024_CUTOFF else "POST_2024"
    parsed_origin = to_decimal(origin_usd) if origin_usd not in (None, "") else Decimal("0")
    if regime == "POST_2024":
        parsed_origin = Decimal("0")
    if parsed_origin < 0:
        raise ValueError("Origem US nao pode ser negativa.")
    if parsed_origin > total_usd:
        raise ValueError("Origem US nao pode exceder o valor total em USD.")

    ptax = get_ptax(event_row["event_date"], conn=conn)
    price_usd = total_usd / quantity
    origin_brl_usd = total_usd - parsed_origin
    cost_brl_portion_brl = origin_brl_usd * ptax["venda"]

    cur = conn.execute(
        """
        INSERT INTO fiscal_lots (
            portfolio_id, asset_id, event_id, date, quantity, price_usd,
            total_usd, origin_usd, origin_brl_usd, ptax_venda_acq,
            ptax_compra_acq, cost_brl_portion_brl, cost_usd_portion_usd,
            regime, quantity_remaining
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            event_row["portfolio_id"],
            event_row["asset_id"],
            event_row["id"],
            event_row["event_date"],
            str(quantity),
            str(price_usd),
            str(total_usd),
            str(parsed_origin),
            str(origin_brl_usd),
            str(ptax["venda"]),
            str(ptax["compra"]),
            str(cost_brl_portion_brl),
            str(parsed_origin),
            regime,
            str(quantity),
        ),
    )
    row = conn.execute(
        "SELECT * FROM fiscal_lots WHERE id = ?",
        (cur.lastrowid,),
    ).fetchone()
    return dict(row)
